### PR TITLE
Ubuntu dev

### PR DESCRIPTION
**Pull request by ClangWU**
The previous version did not support running on Linux platform.Now it's OK.

### CODE REVIEW

**Comment by zhanglingfeng911** [comment]
你怎么编译的过的啊，我在ubantu18.04LTS版本上编译，报这个错误
Consolidate compiler generated dependencies of target core
[ 92%] Built target core
Consolidate compiler generated dependencies of target welding_robot
[ 96%] Linking CXX executable bin/welding_robot
/usr/bin/x86_64-linux-gnu-ld: 找不到 -lws2_32
/usr/bin/x86_64-linux-gnu-ld: 找不到 -lwinmm
collect2: error: ld returned 1 exit status
CMakeFiles/welding_robot.dir/build.make:101: recipe for target 'bin/welding_robot' failed
make[2]: *** [bin/welding_robot] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/welding_robot.dir/all' failed
make[1]: *** [CMakeFiles/welding_robot.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhanglingfeng911** [comment]
> The previous version did not support running on Linux platform.Now it's OK.

你怎么编译的过的啊，我在ubantu18.04LTS版本上编译，报这个错误
Consolidate compiler generated dependencies of target core
[ 92%] Built target core
Consolidate compiler generated dependencies of target welding_robot
[ 96%] Linking CXX executable bin/welding_robot
/usr/bin/x86_64-linux-gnu-ld: 找不到 -lws2_32
/usr/bin/x86_64-linux-gnu-ld: 找不到 -lwinmm
collect2: error: ld returned 1 exit status
CMakeFiles/welding_robot.dir/build.make:101: recipe for target 'bin/welding_robot' failed
make[2]: *** [bin/welding_robot] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/welding_robot.dir/all' failed
make[1]: *** [CMakeFiles/welding_robot.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mhsitu** [comment]
> 

看起来是链接的问题，刚查看了coppeliasim文件夹下的cmakelists文件里，错误是链接了Windows里的两个库，建议尝试修改：
1.把判断unix或者Windows的条件去掉，直接只链接unix下的库，删除Windows下要链接的两库

**Comment by zhanglingfeng911** [comment]
谢谢大佬 刚已经解决了 参考了vrep_template代码库的cmakelist文件，还有就是它还少链接了pthread库



发自我的iPhone


------------------ Original ------------------
From: Stuart ***@***.***&gt;
Date: Sun,Jan 23,2022 3:13 PM
To: mhsitu/welding_robot ***@***.***&gt;
Cc: zlf ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [mhsitu/welding_robot] Ubuntu dev (#1)





   
看起来是链接的问题，刚查看了coppeliasim文件夹下的cmakelists文件里，错误是链接了Windows里的两个库，建议尝试修改：
 1.把判断unix或者Windows的条件去掉，直接只链接unix下的库，删除Windows下要链接的两库
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanglingfeng911** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        大佬您好，请问为啥这里面没有这个文件呀          ./files/cubic_weld_points.in ？ 然后指针就为空，程序core掉了。。。
    
     
    
        
                    ***@***.***
        
    
 

    On 1/23/2022 ***@***.***> wrote： 


谢谢大佬 刚已经解决了 参考了vrep_template代码库的cmakelist文件，还有就是它还少链接了pthread库发自我的iPhone------------------ Original ------------------From: Stuart ***@***.***>Date: Sun,Jan 23,2022 3:13 PMTo: mhsitu/welding_robot ***@***.***>Cc: zlf ***@***.***>, Comment ***@***.***>Subject: Re: [mhsitu/welding_robot] Ubuntu dev (#1)


看起来是链接的问题，刚查看了coppeliasim文件夹下的cmakelists文件里，错误是链接了Windows里的两个库，建议尝试修改：
1.把判断unix或者Windows的条件去掉，直接只链接unix下的库，删除Windows下要链接的两库

**Pull request merged**
